#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpansesWPF.BudzetBuddy
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Expanses")]
	public partial class ExpansesDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCategories(Categories instance);
    partial void UpdateCategories(Categories instance);
    partial void DeleteCategories(Categories instance);
    partial void InsertMonths(Months instance);
    partial void UpdateMonths(Months instance);
    partial void DeleteMonths(Months instance);
    partial void InsertMonthlyExpanses(MonthlyExpanses instance);
    partial void UpdateMonthlyExpanses(MonthlyExpanses instance);
    partial void DeleteMonthlyExpanses(MonthlyExpanses instance);
    partial void InsertExpanses(Expanses instance);
    partial void UpdateExpanses(Expanses instance);
    partial void DeleteExpanses(Expanses instance);
    partial void InsertUsers(Users instance);
    partial void UpdateUsers(Users instance);
    partial void DeleteUsers(Users instance);
    #endregion
		
		public ExpansesDBDataContext() : 
				base(global::ExpansesWPF.Properties.Settings.Default.ExpansesConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public ExpansesDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExpansesDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExpansesDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExpansesDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Categories> Categories
		{
			get
			{
				return this.GetTable<Categories>();
			}
		}
		
		public System.Data.Linq.Table<Months> Months
		{
			get
			{
				return this.GetTable<Months>();
			}
		}
		
		public System.Data.Linq.Table<MonthlyExpanses> MonthlyExpanses
		{
			get
			{
				return this.GetTable<MonthlyExpanses>();
			}
		}
		
		public System.Data.Linq.Table<Expanses> Expanses
		{
			get
			{
				return this.GetTable<Expanses>();
			}
		}
		
		public System.Data.Linq.Table<Users> Users
		{
			get
			{
				return this.GetTable<Users>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categories")]
	public partial class Categories : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _categories_ID;
		
		private string _categories_name;
		
		private int _categories_usr_ID;
		
		private System.DateTime _categories_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncategories_IDChanging(int value);
    partial void Oncategories_IDChanged();
    partial void Oncategories_nameChanging(string value);
    partial void Oncategories_nameChanged();
    partial void Oncategories_usr_IDChanging(int value);
    partial void Oncategories_usr_IDChanged();
    partial void Oncategories_dateChanging(System.DateTime value);
    partial void Oncategories_dateChanged();
    #endregion
		
		public Categories()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categories_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int categories_ID
		{
			get
			{
				return this._categories_ID;
			}
			set
			{
				if ((this._categories_ID != value))
				{
					this.Oncategories_IDChanging(value);
					this.SendPropertyChanging();
					this._categories_ID = value;
					this.SendPropertyChanged("categories_ID");
					this.Oncategories_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categories_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string categories_name
		{
			get
			{
				return this._categories_name;
			}
			set
			{
				if ((this._categories_name != value))
				{
					this.Oncategories_nameChanging(value);
					this.SendPropertyChanging();
					this._categories_name = value;
					this.SendPropertyChanged("categories_name");
					this.Oncategories_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categories_usr_ID", DbType="Int NOT NULL")]
		public int categories_usr_ID
		{
			get
			{
				return this._categories_usr_ID;
			}
			set
			{
				if ((this._categories_usr_ID != value))
				{
					this.Oncategories_usr_IDChanging(value);
					this.SendPropertyChanging();
					this._categories_usr_ID = value;
					this.SendPropertyChanged("categories_usr_ID");
					this.Oncategories_usr_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categories_date", DbType="DateTime NOT NULL")]
		public System.DateTime categories_date
		{
			get
			{
				return this._categories_date;
			}
			set
			{
				if ((this._categories_date != value))
				{
					this.Oncategories_dateChanging(value);
					this.SendPropertyChanging();
					this._categories_date = value;
					this.SendPropertyChanged("categories_date");
					this.Oncategories_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Months")]
	public partial class Months : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mth_ID;
		
		private string _mth_name;
		
		private int _mth_number;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmth_IDChanging(int value);
    partial void Onmth_IDChanged();
    partial void Onmth_nameChanging(string value);
    partial void Onmth_nameChanged();
    partial void Onmth_numberChanging(int value);
    partial void Onmth_numberChanged();
    #endregion
		
		public Months()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mth_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mth_ID
		{
			get
			{
				return this._mth_ID;
			}
			set
			{
				if ((this._mth_ID != value))
				{
					this.Onmth_IDChanging(value);
					this.SendPropertyChanging();
					this._mth_ID = value;
					this.SendPropertyChanged("mth_ID");
					this.Onmth_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mth_name", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string mth_name
		{
			get
			{
				return this._mth_name;
			}
			set
			{
				if ((this._mth_name != value))
				{
					this.Onmth_nameChanging(value);
					this.SendPropertyChanging();
					this._mth_name = value;
					this.SendPropertyChanged("mth_name");
					this.Onmth_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mth_number", DbType="Int NOT NULL")]
		public int mth_number
		{
			get
			{
				return this._mth_number;
			}
			set
			{
				if ((this._mth_number != value))
				{
					this.Onmth_numberChanging(value);
					this.SendPropertyChanging();
					this._mth_number = value;
					this.SendPropertyChanged("mth_number");
					this.Onmth_numberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MonthlyExpanses")]
	public partial class MonthlyExpanses : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _expsm_ID;
		
		private string _expsm_Category;
		
		private decimal _expsm_Price;
		
		private string _expsm_Description;
		
		private System.DateTime _expsm_date;
		
		private int _expsm_day;
		
		private System.Nullable<int> _expsm_usr_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onexpsm_IDChanging(int value);
    partial void Onexpsm_IDChanged();
    partial void Onexpsm_CategoryChanging(string value);
    partial void Onexpsm_CategoryChanged();
    partial void Onexpsm_PriceChanging(decimal value);
    partial void Onexpsm_PriceChanged();
    partial void Onexpsm_DescriptionChanging(string value);
    partial void Onexpsm_DescriptionChanged();
    partial void Onexpsm_dateChanging(System.DateTime value);
    partial void Onexpsm_dateChanged();
    partial void Onexpsm_dayChanging(int value);
    partial void Onexpsm_dayChanged();
    partial void Onexpsm_usr_IDChanging(System.Nullable<int> value);
    partial void Onexpsm_usr_IDChanged();
    #endregion
		
		public MonthlyExpanses()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expsm_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int expsm_ID
		{
			get
			{
				return this._expsm_ID;
			}
			set
			{
				if ((this._expsm_ID != value))
				{
					this.Onexpsm_IDChanging(value);
					this.SendPropertyChanging();
					this._expsm_ID = value;
					this.SendPropertyChanged("expsm_ID");
					this.Onexpsm_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expsm_Category", DbType="NChar(25) NOT NULL", CanBeNull=false)]
		public string expsm_Category
		{
			get
			{
				return this._expsm_Category;
			}
			set
			{
				if ((this._expsm_Category != value))
				{
					this.Onexpsm_CategoryChanging(value);
					this.SendPropertyChanging();
					this._expsm_Category = value;
					this.SendPropertyChanged("expsm_Category");
					this.Onexpsm_CategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expsm_Price", DbType="Decimal(18,2) NOT NULL")]
		public decimal expsm_Price
		{
			get
			{
				return this._expsm_Price;
			}
			set
			{
				if ((this._expsm_Price != value))
				{
					this.Onexpsm_PriceChanging(value);
					this.SendPropertyChanging();
					this._expsm_Price = value;
					this.SendPropertyChanged("expsm_Price");
					this.Onexpsm_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expsm_Description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string expsm_Description
		{
			get
			{
				return this._expsm_Description;
			}
			set
			{
				if ((this._expsm_Description != value))
				{
					this.Onexpsm_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._expsm_Description = value;
					this.SendPropertyChanged("expsm_Description");
					this.Onexpsm_DescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expsm_date", DbType="Date NOT NULL")]
		public System.DateTime expsm_date
		{
			get
			{
				return this._expsm_date;
			}
			set
			{
				if ((this._expsm_date != value))
				{
					this.Onexpsm_dateChanging(value);
					this.SendPropertyChanging();
					this._expsm_date = value;
					this.SendPropertyChanged("expsm_date");
					this.Onexpsm_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expsm_day", DbType="Int NOT NULL")]
		public int expsm_day
		{
			get
			{
				return this._expsm_day;
			}
			set
			{
				if ((this._expsm_day != value))
				{
					this.Onexpsm_dayChanging(value);
					this.SendPropertyChanging();
					this._expsm_day = value;
					this.SendPropertyChanged("expsm_day");
					this.Onexpsm_dayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expsm_usr_ID", DbType="Int")]
		public System.Nullable<int> expsm_usr_ID
		{
			get
			{
				return this._expsm_usr_ID;
			}
			set
			{
				if ((this._expsm_usr_ID != value))
				{
					this.Onexpsm_usr_IDChanging(value);
					this.SendPropertyChanging();
					this._expsm_usr_ID = value;
					this.SendPropertyChanged("expsm_usr_ID");
					this.Onexpsm_usr_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Expanses")]
	public partial class Expanses : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _exps_ID;
		
		private string _exps_Category;
		
		private decimal _exps_Price;
		
		private string _exps_Description;
		
		private System.Nullable<System.DateTime> _exps_date;
		
		private System.Nullable<int> _exps_usr_ID;
		
		private System.Nullable<int> _exps_monthlyExps_ID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onexps_IDChanging(int value);
    partial void Onexps_IDChanged();
    partial void Onexps_CategoryChanging(string value);
    partial void Onexps_CategoryChanged();
    partial void Onexps_PriceChanging(decimal value);
    partial void Onexps_PriceChanged();
    partial void Onexps_DescriptionChanging(string value);
    partial void Onexps_DescriptionChanged();
    partial void Onexps_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onexps_dateChanged();
    partial void Onexps_usr_IDChanging(System.Nullable<int> value);
    partial void Onexps_usr_IDChanged();
    partial void Onexps_monthlyExps_IDChanging(System.Nullable<int> value);
    partial void Onexps_monthlyExps_IDChanged();
    #endregion
		
		public Expanses()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exps_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int exps_ID
		{
			get
			{
				return this._exps_ID;
			}
			set
			{
				if ((this._exps_ID != value))
				{
					this.Onexps_IDChanging(value);
					this.SendPropertyChanging();
					this._exps_ID = value;
					this.SendPropertyChanged("exps_ID");
					this.Onexps_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exps_Category", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string exps_Category
		{
			get
			{
				return this._exps_Category;
			}
			set
			{
				if ((this._exps_Category != value))
				{
					this.Onexps_CategoryChanging(value);
					this.SendPropertyChanging();
					this._exps_Category = value;
					this.SendPropertyChanged("exps_Category");
					this.Onexps_CategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exps_Price", DbType="Decimal(18,2) NOT NULL")]
		public decimal exps_Price
		{
			get
			{
				return this._exps_Price;
			}
			set
			{
				if ((this._exps_Price != value))
				{
					this.Onexps_PriceChanging(value);
					this.SendPropertyChanging();
					this._exps_Price = value;
					this.SendPropertyChanged("exps_Price");
					this.Onexps_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exps_Description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string exps_Description
		{
			get
			{
				return this._exps_Description;
			}
			set
			{
				if ((this._exps_Description != value))
				{
					this.Onexps_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._exps_Description = value;
					this.SendPropertyChanged("exps_Description");
					this.Onexps_DescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exps_date", DbType="Date")]
		public System.Nullable<System.DateTime> exps_date
		{
			get
			{
				return this._exps_date;
			}
			set
			{
				if ((this._exps_date != value))
				{
					this.Onexps_dateChanging(value);
					this.SendPropertyChanging();
					this._exps_date = value;
					this.SendPropertyChanged("exps_date");
					this.Onexps_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exps_usr_ID", DbType="Int")]
		public System.Nullable<int> exps_usr_ID
		{
			get
			{
				return this._exps_usr_ID;
			}
			set
			{
				if ((this._exps_usr_ID != value))
				{
					this.Onexps_usr_IDChanging(value);
					this.SendPropertyChanging();
					this._exps_usr_ID = value;
					this.SendPropertyChanged("exps_usr_ID");
					this.Onexps_usr_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exps_monthlyExps_ID", DbType="Int")]
		public System.Nullable<int> exps_monthlyExps_ID
		{
			get
			{
				return this._exps_monthlyExps_ID;
			}
			set
			{
				if ((this._exps_monthlyExps_ID != value))
				{
					this.Onexps_monthlyExps_IDChanging(value);
					this.SendPropertyChanging();
					this._exps_monthlyExps_ID = value;
					this.SendPropertyChanged("exps_monthlyExps_ID");
					this.Onexps_monthlyExps_IDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class Users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usr_ID;
		
		private string _usr_Login;
		
		private string _usr_Password;
		
		private System.DateTime _usr_date;
		
		private System.Nullable<bool> _usr_IsAdmin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusr_IDChanging(int value);
    partial void Onusr_IDChanged();
    partial void Onusr_LoginChanging(string value);
    partial void Onusr_LoginChanged();
    partial void Onusr_PasswordChanging(string value);
    partial void Onusr_PasswordChanged();
    partial void Onusr_dateChanging(System.DateTime value);
    partial void Onusr_dateChanged();
    partial void Onusr_IsAdminChanging(System.Nullable<bool> value);
    partial void Onusr_IsAdminChanged();
    #endregion
		
		public Users()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usr_ID
		{
			get
			{
				return this._usr_ID;
			}
			set
			{
				if ((this._usr_ID != value))
				{
					this.Onusr_IDChanging(value);
					this.SendPropertyChanging();
					this._usr_ID = value;
					this.SendPropertyChanged("usr_ID");
					this.Onusr_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_Login", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usr_Login
		{
			get
			{
				return this._usr_Login;
			}
			set
			{
				if ((this._usr_Login != value))
				{
					this.Onusr_LoginChanging(value);
					this.SendPropertyChanging();
					this._usr_Login = value;
					this.SendPropertyChanged("usr_Login");
					this.Onusr_LoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usr_Password
		{
			get
			{
				return this._usr_Password;
			}
			set
			{
				if ((this._usr_Password != value))
				{
					this.Onusr_PasswordChanging(value);
					this.SendPropertyChanging();
					this._usr_Password = value;
					this.SendPropertyChanged("usr_Password");
					this.Onusr_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_date", DbType="DateTime NOT NULL")]
		public System.DateTime usr_date
		{
			get
			{
				return this._usr_date;
			}
			set
			{
				if ((this._usr_date != value))
				{
					this.Onusr_dateChanging(value);
					this.SendPropertyChanging();
					this._usr_date = value;
					this.SendPropertyChanged("usr_date");
					this.Onusr_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usr_IsAdmin", DbType="Bit")]
		public System.Nullable<bool> usr_IsAdmin
		{
			get
			{
				return this._usr_IsAdmin;
			}
			set
			{
				if ((this._usr_IsAdmin != value))
				{
					this.Onusr_IsAdminChanging(value);
					this.SendPropertyChanging();
					this._usr_IsAdmin = value;
					this.SendPropertyChanged("usr_IsAdmin");
					this.Onusr_IsAdminChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
