<?xml version="1.0" encoding="utf-8"?><Database Name="Expanses" Class="ExpansesDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Expanses;User ID=lk;Connect Timeout=30;Encrypt=False;Trust Server Certificate=True" SettingsObjectName="ExpansesWPF.Properties.Settings" SettingsPropertyName="ExpansesConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="usr_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="usr_Login" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="usr_Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="usr_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Categories">
      <Column Name="categories_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="categories_name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="categories_usr_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="categories_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Months" Member="Months">
    <Type Name="Months">
      <Column Name="mth_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mth_name" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="mth_number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MonthlyExpanses" Member="MonthlyExpanses">
    <Type Name="MonthlyExpanses">
      <Column Name="expsm_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="expsm_Category" Type="System.String" DbType="NChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="expsm_Price" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="expsm_Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="expsm_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="expsm_day" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="expsm_usr_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Expanses" Member="Expanses">
    <Type Name="Expanses">
      <Column Name="exps_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="exps_Category" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="exps_Price" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="exps_Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="exps_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="exps_usr_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="exps_monthlyExps_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>